# Generated by Django 3.1.7 on 2021-02-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='placeholder',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.gallery'),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.picture'),
        ),
    ]
