# Generated by Django 3.1.6 on 2021-02-21 17:14

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default=apps.users.models.get_default_profile_username, max_length=255, unique=True),
        ),
    ]
